language: php

php:
  - 5.4

notifications:
  campfire:
    rooms:
      secure: ce8kUR0vS0Mz9vL7fpCkED0Or7qzSFerXZBPLhpGZF+yLbnOJGbd9PiZvPvpG5LLUCZPlXioIS/dTrFznH83qGldrWIhYBuWvIUzjoORI8mvi4HoZ+L6gOBGKMxXPiEftKXE0k92k1gllSRq5nXrO1274iouFUSiDYjM23DQF40=

script:
  - phpunit --coverage-clover build/logs/clover.xml

before_script:
  - mkdir -p build/logs
  - composer install
  - mysql -e 'create database `test-promotions`;'
  - mysql --default-character-set=utf8 test-promotions < tests/test_data/structure.sql

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
