language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
  slack:
    secure: jkZDWqI+za7mMP1RnozFmsB6SM2THjp59elBEpMrewjG270NpCdB2fCc2XFSeHVJ1vyPax/Q139CsWhctpD4smA4An1GmTsvQyVcWVvKsqsrTG0q22cBx+WKJKL9cwxQ+UQSbvySVCY6V3oXaqmaPBK97oqHZOc+FET2Z9WDHhc=

install:
  - travis_retry composer install --no-interaction --no-progress --prefer-dist

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `OpenBuildings/promotions`;'
  - mysql --default-character-set=utf8 OpenBuildings/promotions < tests/test_data/structure.sql

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
